project_id = "ohuzblalbmgykwaaecds"

[functions.generate-investment-suggestions]
verify_jwt = true

[functions.update-stock-prices]
verify_jwt = false

[functions.generate-trading-signals]
verify_jwt = true

[functions.execute-auto-trades]
verify_jwt = false

[functions.monitor-positions]
verify_jwt = false

[functions.backtest-strategy]
verify_jwt = true

[functions.update-broker-credentials]
verify_jwt = true

[functions.check-broker-credentials]
verify_jwt = true