project_id = "ohuzblalbmgykwaaecds"

[functions.generate-investment-suggestions]
verify_jwt = true

[functions.update-stock-prices]
verify_jwt = false

[functions.generate-trading-signals]
verify_jwt = false