project_id = "ohuzblalbmgykwaaecds"

[functions.generate-investment-suggestions]
verify_jwt = false

[functions.update-stock-prices]
verify_jwt = false

[functions.generate-trading-signals]
verify_jwt = false

[functions.execute-auto-trades]
verify_jwt = false

[functions.monitor-positions]
verify_jwt = false